name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set Environment Variable
        run: |
          echo "build=begin" >> $GITHUB_ENV
        shell: bash

      - name: Get Environment Cache
        id: environment-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
          key: tgfx-environment-ios-20231129
          restore-keys: tgfx-environment-ios-

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            third_party
          key: third-party-ios-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}
          restore-keys: third-party-ios-

      - name: Install Build Tools
        run: |
          chmod +x install_tools.sh
          ./install_tools.sh
        shell: bash

      - name: Run depsync
        run: |
          npm install depsync -g
          depsync
        shell: bash

      - name: Build iOS
        run: |
          cd ios
          node gen_ios
          xcodebuild -workspace Hello2D.xcworkspace -scheme Hello2D -configuration Release -sdk iphoneos -arch arm64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Save Environment Cache
        if: ${{ (github.event_name == 'push') && (steps.environment-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v4
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
          key: tgfx-environment-ios-20231129

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v4
        with:
          path: |
            third_party
          key: third-party-ios-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}

      - name: Job Failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ios_build
          path: ios
  dispatch:
    runs-on: ubuntu-latest
    needs: [ ios ]
    steps:
      - name: Record build_complete status
        run: echo "build_complete=true" >> $GITHUB_ENV
      - name: Trigger repository_dispatch for build
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"build_complete"}'