name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"

  android:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"

  web:
    runs-on: windows-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"

  win:
    runs-on: windows-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"

  qt:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Empty Task 1
        run: echo "Executing Task 1" && sleep 1

      - name: Execute Empty Task 2
        run: echo "Executing Task 2" && sleep 1

      - name: Execute Empty Task 3
        run: echo "Executing Task 3" && sleep 1

      - name: Return Success
        run: echo "All tasks executed successfully"