name: Trigger Webhook on Push, PR, PR Merge, and All Checks Passed

on:
  pull_request:
    types:
      - opened
  repository_dispatch:
    types:
      - webhook_trigger

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send Webhook on PR
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 收到新的拉取请求：\n请求者: ${{ github.actor }}\nPR 标题: ${{ github.event.pull_request.title }}\nPR 链接: ${{ github.event.pull_request.html_url }}"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}

    - name: Send Webhook on Repository Dispatch
      if: github.event_name == 'repository_dispatch' && github.event.action == 'webhook_trigger'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "msgtype": "text",
              "text": {
                "content": "仓库 ${{ github.repository }} 的构建和测试已完成。"
              }
            }' \
        https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}