name: notify

on:
  workflow_run:
    workflows:
      - autotest
      - build
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Send Both Complete Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "仓库 ${{ github.repository }} 的构建和测试已完成。"
                }
              }' \
          https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}