name: notify

on:
  repository_dispatch:
    types: [build_complete, autotest_complete]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "仓库 ${{ github.repository }} 的事件 ${{ github.event.action }} 已完成。事件类型：${{ github.event.client_payload.trigger_event }}。"
                }
              }' \
          https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHAT_WEBHOOK_KEY }}